name: "📁 Техническая задача / Meta issue"
description: "Используйте этот тип задач только по прямой просьбе создателя сборки"
title: "[Meta]: "
labels: ["meta"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📁 Внутренняя техническая задача проекта Ultimate Optimization
  - type: textarea
    id: meta_info
    attributes:
      label: "Технические подробности крупной девелоперской задачи / Details"
      placeholder: "Глобальный перевод сборки на новую версию Minecraft 1.21.x и масштабные тесты стабильности FPS на разных видеокартах..."
    validations:
      required: true
  - type: checkboxes
    id: user_agreement_meta
    attributes:
      label: "⚖️ Ограничение доступа / Developer Access Only"
      options:
        - label: "Я являюсь разработчиком/модератором сборки Ultimate Optimization или создатель проекта лично попросил меня создать эту техническую задачу / Developer access confirmed"
          required: true
