name: "💡 Запрос нового мода / Mod request"
description: "Предложите новый мод на FPS или графику для добавления в Ultimate Optimization"
title: "[Mod Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### 💡 Предложение мода для Ultimate Optimization / Mod suggestion form
  - type: input
    id: mod_name
    attributes:
      label: "Название мода / Mod Name"
      placeholder: "Например: Lithium, Sodium, Bobby, ImmediatelyFast..."
    validations:
      required: true
  - type: input
    id: mod_link
    attributes:
      label: "Ссылка на мод / Mod Link"
      placeholder: "https://modrinth.com..."
    validations:
      required: true
  - type: textarea
    id: reasoning
    attributes:
      label: "Зачем этот мод нужен в сборке? / Why should it be added?"
      placeholder: "Этот мод оптимизирует работу чанков, уменьшает нагрузку на процессор и поднимает FPS..."
    validations:
      required: true
