name: "❌ Удаление мода / Mod removal"
description: "Предложите убрать какой-то мод из сборки Ultimate Optimization"
title: "[Mod Removal]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### ❌ Запрос на удаление мода из Ultimate Optimization / Mod removal form
  - type: input
    id: remove_mod
    attributes:
      label: "1. Какой мод нужно удалить? / Mod to remove"
      placeholder: "Например: Reese's Sodium Options..."
    validations:
      required: true
  - type: textarea
    id: remove_reason
    attributes:
      label: "2. Почему его нужно убрать? / Why should it be removed?"
      placeholder: "Этот мод конфликтует с новой версией Java 25 и вызывает микрофризы каждые 5 секунд при рендере..."
    validations:
      required: true
  - type: dropdown
    id: removal_os
    attributes:
      label: "3. Операционная система / Operating System"
      options:
        - "🪟 Windows 10 / 11"
        - "🐧 Linux"
        - "🍏 MacOS"
        - "📱 PojavLauncher"
        - "❓ Другая ОС"
    validations:
      required: true
  - type: dropdown
    id: removal_drive
    attributes:
      label: "4. Проблема с модом зависит от типа вашего диска? / Storage Drive Type"
      options:
        - "💾 Да, из-за этого мода игра фризит и тормозит именно на жестких дисках HDD"
        - "🚀 Лагает/багует на любых накопителях одинаково (и на SSD, и на HDD)"
    validations:
      required: true
  - type: textarea
    id: removal_specs_fps
    attributes:
      label: "5. Приблизительный тест с модом, который хотите удалить, и ваши комплектующие (видюха, ссд и т.д.) / Your Specs & Test FPS"
      placeholder: "Укажите параметры вашего ПК (Видеокарта, Процессор, SSD/HDD, RAM) и ваши замеры кадров в секунду (FPS) с этим модом и без него..."
    validations:
      required: true
  - type: checkboxes
    id: user_agreement_removal
    attributes:
      label: "⚖️ Пользовательское соглашение / User Agreement"
      options:
        - label: "Я понимаю, что удаление важных системных модов может сломать общую оптимизацию сборки. Моё предложение подкреплено личными техническими тестами FPS / I agree to the terms"
          required: true
